---
- name: generate systemd unit file
  template:
    src: etcd.service.j2
    dest: /usr/lib/systemd/system/etcd.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart etcd
  tags:
    - etcd

- name: install consul check script
  template:
    src: check-etcd-member
    dest: /usr/local/bin
    mode: 0755
  tags:
    - etcd

- name: enable and start etcd
  service:
    name: etcd
    enabled: yes
    state: started
  tags:
    - etcd

- meta: flush_handlers
